# Generated by Django 2.2.16 on 2021-08-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("name",),
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
    ]
